### ISSUE TITLE
Attribute value not pulled to the control

### ISSUE THREAD

**Issue by rx294** [mitre/microsoft-windows-2012r2-memberserver-stig-baseline#31]
https://github.com/mitre/microsoft-windows-2012r2-memberserver-stig-baseline/blob/11122d9f6771acfcb221d2d36a02102d843e4ad4/controls/V-1127.rb#L73

ADMINISTRATORS should be populated using attribute('administrators')

**Comment by asturtevant** [comment]
Updated the control
